Experiment with depth(number of layers)

Model 1:
Build a model with one hidden layer, and train it
Find the vaalidation accuracy.
(128)

Model 2:
Build a model with 3 hidden layers and train it
Find the vaalidation accuracy.   
(1024,512,256)

Model 3:
Build a model with 5 hidden layers and 
Find the vaalidation accuracy
(1024,512,256,128,64)


plot the vaalidation accuracy for all 3 models in a single plot

plot the vaalidation loss for all 3 models

In [1]:
#import libraries
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Flatten
from keras.datasets import cifar10
from keras.optimizers import SGD,RMSprop
from keras.utils import to_categorical
import matplotlib.pyplot as plt

#Load the Data
(x_train,y_train),(x_test,y_test)=cifar10.load_data()
print(x_train.dtype)
print(x_train.shape)
print(y_test.shape)
print(x_train[0])

#plt.imshow(x_train[0])
#plt.show()
print("***************************")
#print(f"label is :{y_train[0]}")

#normalize
x_train = x_train.astype('float32')/255.0
x_test  = x_test.astype('float32')/255.0

#to_categorical
print(f"before : label is :{y_train[0]}")
y_train = to_categorical(y_train)
print(f"after : label is :{y_train[0]}")
print(f"after : label is :{y_train[100]}")
y_test = to_categorical(y_test)



uint8
(50000, 32, 32, 3)
(10000, 1)
[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]
***************************
before : label is :[6]
after : label is :[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
after : label is :[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [2]:
model = Sequential()
model.add(Flatten(input_shape =(32,32,3)))
model.add(Dense(128,'relu'))  #layer containg 128 neuron 
model.add(Dense(10,'softmax'))       #10 neurons last layer
model.compile(optimizer=SGD(learning_rate=0.01),loss='categorical_crossentropy',metrics=['accuracy'])
#Train
result=model.fit(x_train,y_train,epochs=10,batch_size=64,validation_split=0.2) #64 images are sent each time


d:\Day2_AI\ai_bootcamp\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.2992 - loss: 1.9565 - val_accuracy: 0.3446 - val_loss: 1.8799
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.3657 - loss: 1.8034 - val_accuracy: 0.3755 - val_loss: 1.7889
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.3920 - loss: 1.7367 - val_accuracy: 0.3889 - val_loss: 1.7367
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.4095 - loss: 1.6870 - val_accuracy: 0.4018 - val_loss: 1.7050
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.4239 - loss: 1.6505 - val_accuracy: 0.4028 - val_loss: 1.7028
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.4356 - loss: 1.6148 - val_accuracy: 0.4340 - val_loss: 1.6333
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4459 - loss: 1.5869 - val_accuracy: 0.4323 - val_loss: 1.6266
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.4530 - loss: 1.5634 - val_accuracy: 0.

In [3]:
loss,accuracy = model.evaluate(x_test,y_test)
print(f"test loss:{loss}")
print(f"test accuracy:{accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4525 - loss: 1.5573
test loss:1.5573023557662964
test accuracy:0.45249998569488525


In [4]:
model_SGD= Sequential()
model_SGD.add(Flatten(input_shape =(32,32,3)))
model_SGD.add(Dense(1024,'relu'))  #layer containg 1024 neuron 
model_SGD.add(Dense(512,'relu'))
model_SGD.add(Dense(256,'relu'))
model_SGD.add(Dense(10,'softmax'))       #10 neurons last layer
model_SGD.compile(optimizer=SGD(learning_rate=0.01),loss='categorical_crossentropy',metrics=['accuracy'])
#Train
result2=model_SGD.fit(x_train,y_train,epochs=10,batch_size=64,validation_split=0.2) #64 images are sent each time


Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.3061 - loss: 1.9331 - val_accuracy: 0.3371 - val_loss: 1.8532
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.3846 - loss: 1.7418 - val_accuracy: 0.3965 - val_loss: 1.7110
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4117 - loss: 1.6594 - val_accuracy: 0.4144 - val_loss: 1.6601
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4342 - loss: 1.6011 - val_accuracy: 0.4368 - val_loss: 1.6021
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.4505 - loss: 1.5583 - val_accuracy: 0.4196 - val_loss: 1.6225
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.4638 - loss: 1.5182 - val_accuracy: 0.4526 - val_loss: 1.5489
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4764 - loss: 1.4871 - val_accuracy: 0.4701 - val_loss: 1.5127
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.4859 - loss: 1.4570 - val_acc

In [5]:
loss,accuracy = model_SGD.evaluate(x_test,y_test)
print(f"test loss:{loss}")
print(f"test accuracy:{accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4682 - loss: 1.5055
test loss:1.505507469177246
test accuracy:0.4681999981403351


In [6]:
model_SGD5= Sequential()
model_SGD5.add(Flatten(input_shape =(32,32,3)))
model_SGD5.add(Dense(1024,'relu'))  #layer containg 1024 neuron 
model_SGD5.add(Dense(512,'relu'))
model_SGD5.add(Dense(256,'relu'))
model_SGD5.add(Dense(128,'relu'))
model_SGD5.add(Dense(64,'relu'))
model_SGD5.add(Dense(10,'softmax'))       #10 neurons last layer
model_SGD5.compile(optimizer=SGD(learning_rate=0.01),loss='categorical_crossentropy',metrics=['accuracy'])
#Train
result3=model_SGD5.fit(x_train,y_train,epochs=10,batch_size=64,validation_split=0.2) #64 images are sent each time

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.2810 - loss: 1.9860 - val_accuracy: 0.3182 - val_loss: 1.8671
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.3670 - loss: 1.7714 - val_accuracy: 0.3713 - val_loss: 1.7404
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.3995 - loss: 1.6785 - val_accuracy: 0.4244 - val_loss: 1.6292
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4269 - loss: 1.6108 - val_accuracy: 0.4186 - val_loss: 1.6334
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4447 - loss: 1.5601 - val_accuracy: 0.4201 - val_loss: 1.6176
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.4604 - loss: 1.5172 - val_accuracy: 0.4435 - val_loss: 1.5703
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4702 - loss: 1.4843 - val_accuracy: 0.4688 - val_loss: 1.4927
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 7s 12ms/step - accuracy: 0.4832 - loss: 1.4491 - val_accu

In [7]:
loss,accuracy = model_SGD5.evaluate(x_test,y_test)
print(f"test loss:{loss}")
print(f"test accuracy:{accuracy}")

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4852 - loss: 1.4321
test loss:1.4320850372314453
test accuracy:0.4851999878883362


In [ ]:
plt.plot(result.history['val_accuracy'],label='1-layer',color='red')
plt.plot(result2.history['val_accuracy'],label='3-layer',color='blue')
plt.plot(result3.history['val_accuracy'],label='5-layer',color='green')
plt.title("Val Accuracy of 3 different models")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

In [ ]:
plt.plot(result.history['val_loss'],label='1-layer',color='red')
plt.plot(result2.history['val_loss'],label='3-layer',color='blue')
plt.plot(result3.history['val_loss'],label='5-layer',color='green')
plt.title("Val loss of 3 different models")
plt.xlabel("Epochs")
plt.ylabel("loss")
plt.legend()
plt.show()